const Images = {
  meteorShowerThumbnail: require('./images/cards/meteor-shower-thumbnail.png'),
  meteorShower: require('./images/cards/meteor-shower.png'),
  purpleSkyThumbnail: require('./images/cards/purple-sky-thumbnail.png'),
  purpleSky: require('./images/cards/purple-sky.png'),
  summerSunsetThumbnail: require('./images/cards/summer-sunset-thumbnail.png'),
  summerSunset: require('./images/cards/summer-sunset.png'),

  capeTown: require('./images/cities/cape-town.jpg'),
  london: require('./images/cities/london.jpg'),
  losAngeles: require('./images/cities/los-angeles.jpg'),
  miami: require('./images/cities/miami.jpg'),
  nairobi: require('./images/cities/nairobi.jpg'),
  paris: require('./images/cities/paris.jpg'),
  sanFrancisco: require('./images/cities/san-francisco.jpg'),
  tokyo: require('./images/cities/tokyo.jpg'),

  athleteDispute: require('./images/covers/athlete-dispute.jpg'),
  atlanta: require('./images/covers/atlanta.jpg'),
  deathInParadise: require('./images/covers/death-in-paradise.jpg'),
  fleabag: require('./images/covers/fleabag.jpg'),
  gentlemanJack: require('./images/covers/gentleman-jack.jpg'),
  hometown: require('./images/covers/hometown.jpg'),
  hotProperty: require('./images/covers/hot-property.jpg'),
  killingEve: require('./images/covers/killing-eve.jpg'),
  legends: require('./images/covers/legends.jpg'),
  lineOfDuty: require('./images/covers/line-of-duty.jpg'),
  londonKills: require('./images/covers/london-kills.jpg'),
  luther: require('./images/covers/luther.jpg'),
  mindingTheGap: require('./images/covers/minding-the-gap.jpg'),
  pose: require('./images/covers/pose.jpg'),
  thePlanets: require('./images/covers/the-planets.jpg'),
  topGear: require('./images/covers/top-gear.jpg'),
  worldcup: require('./images/covers/worldcup.jpg'),
  yearsAndYears: require('./images/covers/years-and-years.jpg'),

  story1: require('./images/stories/story1.png'),
  story2: require('./images/stories/story2.png'),
  story3: require('./images/stories/story3.png'),
  story4: require('./images/stories/story4.png'),

  image1: require('./images/1.png'),
  image2: require('./images/2.png'),
  image3: require('./images/3.png'),
  image4: require('./images/4.png'),
  back: require('./images/back.png'),
  backface: require('./images/backface.png'),
  bg: require('./images/bg.png'),
  black: require('./images/black.png'),
  blue: require('./images/blue.png'),
  card1: require('./images/card1.png'),
  card2: require('./images/card2.png'),
  card3: require('./images/card3.png'),
  card4: require('./images/card4.png'),
  card5: require('./images/card5.png'),
  card6: require('./images/card6.png'),
  chess: require('./images/chess.jpg'),
  experiences: require('./images/experiences.jpg'),
  fitness: require('./images/fitness.jpg'),
  front: require('./images/front.png'),
  green: require('./images/green.png'),
  homes: require('./images/homes.jpg'),
  image: require('./images/image.jpg'),
  janBlomqvistRemoteControl: require('./images/Jan-Blomqvist-Remote-Control.jpg'),
  janBlomqvist: require('./images/Jan-Blomqvist.jpg'),
  loading: require('./images/loading.jpg'),
  orange: require('./images/orange.png'),
  pink: require('./images/pink.png'),
  purple: require('./images/purple.png'),
  queenOfSpade: require('./images/queen-of-spade.png'),
  red: require('./images/red.png'),
  restaurants: require('./images/restaurants.jpg'),
  thebay: require('./images/thebay.jpg'),
  yellow: require('./images/yellow.png'),
  yoga: require('./images/yoga.jpg')
};

export default Images;
